# ─────────────────────────────────────────
# report_router.py  (Gemini 피드백 자동생성 포함)
# ─────────────────────────────────────────
import io
from datetime import datetime
from typing import Any, Optional

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_RIGHT, TA_CENTER
from reportlab.pdfgen import canvas
from pathlib import Path
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.fonts import addMapping

# gemini_feedback 모듈 (없으면 graceful fallback)
try:
    from gemini_feedback import generate_feedback as _generate_feedback
    HAS_GEMINI = True
except ImportError:
    HAS_GEMINI = False
    _generate_feedback = None

report_router = APIRouter(prefix="/analysis", tags=["report"])

BASE_DIR = Path(__file__).resolve().parent
FONT_DIR = BASE_DIR.parent / "assets"

def register_korean_fonts() -> bool:
    reg  = FONT_DIR / "NotoSansKR-Regular.ttf"
    bold = FONT_DIR / "NotoSansKR-Bold.ttf"
    if not reg.exists() or not bold.exists():
        return False
    pdfmetrics.registerFont(TTFont("NotoKR", str(reg)))
    pdfmetrics.registerFont(TTFont("NotoKR-Bold", str(bold)))
    addMapping("NotoKR", 0, 0, "NotoKR")
    addMapping("NotoKR", 0, 1, "NotoKR-Bold")
    addMapping("NotoKR", 1, 0, "NotoKR-Bold")
    addMapping("NotoKR", 1, 1, "NotoKR-Bold")
    return True

W, H = A4

# ── 색상 팔레트 ──────────────────────────────────────────────
# 브랜드
C_LIME       = colors.HexColor("#c8f135")   # 메인 포인트
C_LIME_DARK  = colors.HexColor("#9abf1a")   # 진한 라임 (텍스트용)
C_LIME_BG    = colors.HexColor("#f2fadc")   # 라임 연한 배경
C_LIME_BG2   = colors.HexColor("#e8f5c0")   # 라임 중간 배경 (카드 헤더 등)

# 중립
C_BLACK      = colors.HexColor("#111111")
C_DARK       = colors.HexColor("#1e2028")   # 헤더 배경
C_GRAY       = colors.HexColor("#6b7280")
C_LGRAY      = colors.HexColor("#f5f5f7")   # 행 교번 배경
C_BORDER     = colors.HexColor("#e2e8f0")   # 일반 테두리
C_BORDER_DK  = colors.HexColor("#cbd5e1")   # 진한 테두리

# 액센트
C_BLUE       = colors.HexColor("#3b6de8")   # 파랑 (DTW 양호)
C_BLUE_BG    = colors.HexColor("#eff4ff")   # 파랑 연한 배경
C_RED        = colors.HexColor("#e8432d")   # 레드 (오류/경고)
C_RED_BG     = colors.HexColor("#fff1ee")   # 레드 연한 배경
C_ORANGE     = colors.HexColor("#f97316")   # 오렌지 (주의)
C_WHITE      = colors.white


def pct(v: float) -> str: return f"{round(v * 100)}%"
def grade_label(avg: float) -> str:
    if avg >= 0.9: return "S"
    if avg >= 0.7: return "A"
    if avg >= 0.5: return "B"
    return "C"
def grade_color(g: str) -> str:
    return {"S": "#9abf1a", "A": "#3b6de8", "B": "#f97316", "C": "#e8432d"}.get(g, "#111111")


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._pages: list[dict] = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._pages)
        for i, state in enumerate(self._pages):
            self.__dict__.update(state)

            # ── 푸터 텍스트 ──
            try:    self.setFont("NotoKR", 7.5)
            except: self.setFont("Helvetica", 7.5)
            self.setFillColor(colors.HexColor("#9ca3af"))
            self.drawString(20*mm, 6.5*mm, f"Generated by PoseCoach AI  ·  {datetime.now().strftime('%Y.%m.%d')}")
            self.setFillColor(C_LIME)
            self.drawRightString(W - 20*mm, 6.5*mm, f"{i + 1} / {total}")

            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)


# ── Request 모델 ──
class ReportRequest(BaseModel):
    analysis_results: dict[str, Any]
    ai_feedback: Optional[str] = None
    gemini_api_key: Optional[str] = None
    generate_feedback: bool = True


def build_pdf_bytes(req: ReportRequest) -> bytes:
    korean = register_korean_fonts()
    F  = "NotoKR"      if korean else "Helvetica"
    FB = "NotoKR-Bold" if korean else "Helvetica-Bold"

    res      = req.analysis_results
    feedback = req.ai_feedback or ""

    # ── Gemini 피드백 자동 생성 ──
    if not feedback and req.generate_feedback and HAS_GEMINI:
        try:
            feedback = _generate_feedback(
                analysis_results=res,
                api_key=req.gemini_api_key or None,
            ) or ""
        except Exception:
            feedback = ""

    frame_scores = res.get("frame_scores", [])
    error_frames = res.get("error_frames", [])
    dtw_result   = res.get("dtw_result") or {}
    dtw_active   = res.get("dtw_active", False)
    exercise     = res.get("exercise_type", "운동")
    ex_count     = res.get("exercise_count", 0)

    avg_score = (sum(f["score"] for f in frame_scores) / len(frame_scores)) if frame_scores else 0
    dtw_score = dtw_result.get("overall_dtw_score") if dtw_active else None
    combined  = avg_score * 0.7 + dtw_score * 0.3 if dtw_score is not None else avg_score

    by_phase: dict[str, list] = {}
    for f in frame_scores:
        by_phase.setdefault(f["phase"], []).append(f["score"])
    phase_avg = {p: sum(sc) / len(sc) for p, sc in by_phase.items()}
    phase_cnt = {p: len(sc) for p, sc in by_phase.items()}

    err_count: dict[str, int] = {}
    for ef in error_frames:
        for e in ef.get("errors", []):
            err_count[e] = err_count.get(e, 0) + 1
    top_errors = sorted(err_count.items(), key=lambda x: -x[1])[:5]

    # ── 스타일 ──
    sTitle   = ParagraphStyle("title",   fontName=FB, fontSize=20, textColor=C_DARK,  spaceAfter=2,  leading=24)
    sSub     = ParagraphStyle("sub",     fontName=F,  fontSize=9,  textColor=colors.HexColor("#9ca3af"), spaceAfter=0)
    sSection = ParagraphStyle("section", fontName=FB, fontSize=10, textColor=C_DARK,   spaceBefore=10, spaceAfter=5)
    sSmall   = ParagraphStyle("small",   fontName=F,  fontSize=8,  textColor=C_GRAY,   leading=11)
    sBody    = ParagraphStyle("body",    fontName=F,  fontSize=9,  textColor=C_BLACK,  leading=14)
    sRight   = ParagraphStyle("right",   fontName=F,  fontSize=8,  textColor=colors.HexColor("#9ca3af"), alignment=TA_RIGHT)
    sCenter  = ParagraphStyle("center",  fontName=F,  fontSize=8,  textColor=C_GRAY,   alignment=TA_CENTER)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
        leftMargin=18*mm, rightMargin=18*mm, topMargin=10*mm, bottomMargin=22*mm)
    story = []
    usable = W - 36*mm
    ex_kor = {"pushup": "푸시업", "pullup": "풀업"}.get(exercise, exercise)
    grade  = grade_label(avg_score)
    g_hex  = grade_color(grade)

    # ════════════════════════════════════════
    # ① 다크 헤더 블록 (배경색 Table로 구현)
    # ════════════════════════════════════════
    hdr_logo = Paragraph(
        f"<font color='#1111'><b>POSE</b></font><font color='#1111'><b>COACH</b></font>",
        ParagraphStyle("logo", fontName=FB, fontSize=15, textColor=C_WHITE, leading=18)
    )
    hdr_date = Paragraph(
        datetime.now().strftime("%Y.%m.%d"),
        ParagraphStyle("hdr_date", fontName=F, fontSize=8, textColor=colors.HexColor("#9ca3af"), alignment=TA_RIGHT)
    )
    hdr_title = Paragraph(
        f"{ex_kor} 운동 피드백 리포트",
        sTitle
    )
    hdr_grade_badge = Paragraph(
        f"<font color='{g_hex}'><b>{grade} GRADE</b></font>",
        ParagraphStyle("badge", fontName=FB, fontSize=11, textColor=C_WHITE, alignment=TA_RIGHT)
    )

    hdr_top = Table(
        [[hdr_logo, hdr_date]],
        colWidths=[usable * 0.6, usable * 0.4]
    )
    hdr_top.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("LEFTPADDING",  (0,0), (-1,-1), 0),
        ("RIGHTPADDING", (0,0), (-1,-1), 0),
        ("TOPPADDING",   (0,0), (-1,-1), 0),
        ("BOTTOMPADDING",(0,0), (-1,-1), 6),
    ]))
    hdr_bot = Table(
        [[hdr_title, hdr_grade_badge]],
        colWidths=[usable * 0.75, usable * 0.25]
    )
    hdr_bot.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "BOTTOM"),
        ("LEFTPADDING",  (0,0), (-1,-1), 0),
        ("RIGHTPADDING", (0,0), (-1,-1), 0),
        ("TOPPADDING",   (0,0), (-1,-1), 0),
        ("BOTTOMPADDING",(0,0), (-1,-1), 0),
    ]))

    # 다크 배경을 가진 전체 헤더 블록
    header = Table(
    [[hdr_logo, hdr_date],
     [hdr_title, hdr_grade_badge]],
    colWidths=[usable * 0.7, usable * 0.3])

    header.setStyle(TableStyle([
    ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
    ("LEFTPADDING",  (0,0), (-1,-1), 0),
    ("RIGHTPADDING", (0,0), (-1,-1), 0),
    ("TOPPADDING",   (0,0), (-1,-1), 4),
    ("BOTTOMPADDING",(0,0), (-1,-1), 4),
    ("LINEBELOW",    (0,1), (-1,1), 1, C_BORDER_DK),]))

    story.append(header)
    story.append(Spacer(1, 14))

    # ════════════════════════════════════════
    # ② 요약 카드 4개
    # ════════════════════════════════════════
    def _card(label: str, val: str, val_color: str = "#111111", accent_bar: bool = False):
        """라임 상단 바 + 값 카드"""
        content = Table(
            [[Paragraph(f"<font color='{val_color}'><b>{val}</b></font>",
                        ParagraphStyle("cv", fontName=FB, fontSize=17, textColor=C_BLACK, leading=20))],
             [Paragraph(f"<font color='#6b7280' size='7.5'>{label}</font>",
                        ParagraphStyle("cl", fontName=F, fontSize=7.5, textColor=C_GRAY))]],
            colWidths=[None]
        )
        content.setStyle(TableStyle([
            ("LEFTPADDING",  (0,0),(-1,-1), 0),
            ("RIGHTPADDING", (0,0),(-1,-1), 0),
            ("TOPPADDING",   (0,0),(-1,-1), 2),
            ("BOTTOMPADDING",(0,0),(-1,-1), 2),
        ]))
        # 상단 accent 라인 + 내용
        bar_color = C_LIME if accent_bar else C_BORDER_DK
        card_tbl = Table(
            [[""],   # 상단 컬러 바
             [content]],
            colWidths=[None],
            rowHeights=[4, None]
        )
        card_tbl.setStyle(TableStyle([
            ("BACKGROUND",   (0,0),(0,0), bar_color),
            ("BACKGROUND",   (0,1),(0,1), colors.white),
            ("BOX",          (0,0),(-1,-1), 0.6, C_BORDER_DK),
            ("TOPPADDING",   (0,1),(0,1), 10),
            ("BOTTOMPADDING",(0,1),(0,1), 10),
            ("LEFTPADDING",  (0,1),(0,1), 12),
            ("RIGHTPADDING", (0,1),(0,1), 8),
            ("TOPPADDING",   (0,0),(0,0), 0),
            ("BOTTOMPADDING",(0,0),(0,0), 0),
            ("LEFTPADDING",  (0,0),(0,0), 0),
            ("RIGHTPADDING", (0,0),(0,0), 0),
        ]))
        return card_tbl

    cw = (usable - 3*3) / 4   # gap=3 * 3개
    cards_row = Table([[
        _card("운동 횟수",       f"{ex_count}회",  "#111111", accent_bar=True),
        _card("평균 자세 점수",  pct(avg_score),   C_LIME_DARK, accent_bar=True),
        _card(f"종합 점수",      pct(combined),    g_hex,     accent_bar=True),
        _card("오류 프레임",     f"{len(error_frames)}개", "#e8432d", accent_bar=False),
    ]], colWidths=[cw]*4)
    cards_row.setStyle(TableStyle([
        ("LEFTPADDING",  (0,0),(-1,-1), 1),
        ("RIGHTPADDING", (0,0),(-1,-1), 1),
        ("TOPPADDING",   (0,0),(-1,-1), 0),
        ("BOTTOMPADDING",(0,0),(-1,-1), 0),
        ("VALIGN",       (0,0),(-1,-1), "TOP"),
    ]))
    story += [cards_row, Spacer(1, 30)]

    # ════════════════════════════════════════
    # ③ Phase별 자세 점수 (바 차트)
    # ════════════════════════════════════════
    story.append(_section_header("Phase별 자세 점수", FB, F))
    story.append(Spacer(1, 10))

    bar_label_w = 58
    bar_score_w = 40
    bar_cnt_w   = 30
    bar_fill_w  = usable - bar_label_w - bar_score_w - bar_cnt_w

    # 헤더 행
    ph_hdr = Table([[
        Paragraph("<font size='7' color='#9ca3af'>구간</font>",  sSmall),
        Paragraph("", sSmall),
        Paragraph("<font size='7' color='#9ca3af'>점수</font>",  ParagraphStyle("ph1", fontName=F, fontSize=7, textColor=C_GRAY, alignment=TA_RIGHT)),
        Paragraph("<font size='7' color='#9ca3af'>프레임</font>", ParagraphStyle("ph2", fontName=F, fontSize=7, textColor=C_GRAY, alignment=TA_CENTER)),
    ]], colWidths=[bar_label_w, bar_fill_w, bar_score_w, bar_cnt_w], rowHeights=14)
    ph_hdr.setStyle(TableStyle([
        ("VALIGN",       (0,0),(-1,-1),"MIDDLE"),
        ("TOPPADDING",   (0,0),(-1,-1), 0),
        ("BOTTOMPADDING",(0,0),(-1,-1), 2),
        ("LEFTPADDING",  (0,0),(-1,-1), 4),
        ("RIGHTPADDING", (0,0),(-1,-1), 4),
        ("LINEBELOW",    (0,0),(-1,-1), 0.5, C_BORDER_DK),
    ]))
    story.append(ph_hdr)

    for i, (phase, avg) in enumerate(sorted(phase_avg.items(), key=lambda x: -x[1])):
        cnt = phase_cnt.get(phase, 0)
        is_good = avg >= 0.7

        # 채워진 바
        fill_color = C_LIME if is_good else C_ORANGE if avg >= 0.5 else C_RED
        fill_w = max(bar_fill_w * avg, 2)
        empty_w = bar_fill_w - fill_w

        inner_cells = [Paragraph("", sSmall)]
        if empty_w > 0:
            inner = Table([[Paragraph("", sSmall), Paragraph("", sSmall)]],
                          colWidths=[fill_w, empty_w], rowHeights=10)
        else:
            inner = Table([[Paragraph("", sSmall)]], colWidths=[fill_w], rowHeights=10)
        inner.setStyle(TableStyle([
            ("BACKGROUND",   (0,0),(0,0), fill_color),
            ("TOPPADDING",   (0,0),(-1,-1),0),
            ("BOTTOMPADDING",(0,0),(-1,-1),0),
            ("LEFTPADDING",  (0,0),(-1,-1),0),
            ("RIGHTPADDING", (0,0),(-1,-1),0),
        ]))

        bg = C_LGRAY if i % 2 == 1 else colors.white
        score_hex = "#9abf1a" if is_good else "#e8432d"

        row = Table([[
            Paragraph(f"<font size='8.5' color='#374151'>{phase}</font>", sBody),
            inner,
            Paragraph(f"<font color='{score_hex}'><b>{pct(avg)}</b></font>",
                      ParagraphStyle(f"rs_{phase}", fontName=FB, fontSize=9, textColor=C_BLACK, alignment=TA_RIGHT)),
            Paragraph(f"<font size='7' color='#9ca3af'>{cnt}f</font>",
                      ParagraphStyle(f"rc_{phase}", fontName=F, fontSize=7, textColor=C_GRAY, alignment=TA_CENTER)),
        ]], colWidths=[bar_label_w, bar_fill_w, bar_score_w, bar_cnt_w], rowHeights=20)
        row.setStyle(TableStyle([
            ("VALIGN",       (0,0),(-1,-1), "MIDDLE"),
            ("BACKGROUND",   (0,0),(-1,-1), bg),
            ("TOPPADDING",   (0,0),(-1,-1), 2),
            ("BOTTOMPADDING",(0,0),(-1,-1), 2),
            ("LEFTPADDING",  (0,0),(-1,-1), 4),
            ("RIGHTPADDING", (0,0),(-1,-1), 4),
            ("LINEBELOW",    (0,0),(-1,-1), 0.3, C_BORDER),
        ]))
        story.append(row)

    story.append(Spacer(1, 30))

    # ════════════════════════════════════════
    # ④ 주요 자세 오류
    # ════════════════════════════════════════
    story.append(_section_header("주요 자세 오류", FB, F))
    story.append(Spacer(1, 10))

    if top_errors:
        # 헤더
        err_hdr = Table([[
            Paragraph("<font color='#ffffff' size='8'><b>상세 오류</b></font>",
                      ParagraphStyle("eh", fontName=FB, fontSize=8, textColor=C_WHITE)),
            Paragraph("<font color='#ffffff' size='8'><b>횟수</b></font>",
                      ParagraphStyle("ec_h", fontName=FB, fontSize=8, textColor=C_WHITE, alignment=TA_RIGHT)),
        ]], colWidths=[usable * 0.84, usable * 0.16])
        err_hdr.setStyle(TableStyle([
            ("BACKGROUND",   (0,0),(-1,-1), colors.HexColor("#e8432d")),
            ("VALIGN",       (0,0),(-1,-1), "MIDDLE"),
            ("LEFTPADDING",  (0,0),(-1,-1), 10),
            ("RIGHTPADDING", (0,0),(-1,-1), 10),
            ("TOPPADDING",   (0,0),(-1,-1), 10),
            ("BOTTOMPADDING",(0,0),(-1,-1), 10),
            # 왼쪽 강조 라인
            ("LINEBEFORE",   (0,0),(0,-1), 4, colors.HexColor("#c0392b")),
        ]))
        story.append(err_hdr)

        max_cnt = top_errors[0][1] if top_errors else 1
        for i, (err_name, cnt) in enumerate(top_errors):
            bg = C_RED_BG if i % 2 == 0 else colors.white
            ratio = cnt / max_cnt
            # 오류명 + 비율 인라인 바를 함께 표시
            err_row = Table([[
                Paragraph(f"<font size='8.5' color='#1e2028'>{err_name}</font>", sBody),
                Paragraph(
                    f"<font color='#e8432d' size='9'><b>{cnt}회</b></font>",
                    ParagraphStyle(f"er_{i}", fontName=FB, fontSize=9, textColor=C_RED, alignment=TA_RIGHT)
                ),
            ]], colWidths=[usable * 0.84, usable * 0.16])
            err_row.setStyle(TableStyle([
                ("BACKGROUND",   (0,0),(-1,-1), bg),
                ("VALIGN",       (0,0),(-1,-1), "MIDDLE"),
                ("LEFTPADDING",  (0,0),(-1,-1), 10),
                ("RIGHTPADDING", (0,0),(-1,-1), 10),
                ("TOPPADDING",   (0,0),(-1,-1), 10),
                ("BOTTOMPADDING",(0,0),(-1,-1), 10),
                ("LINEBELOW",    (0,0),(-1,-1), 0.4, C_BORDER),
                # 비율에 따른 왼쪽 강도 바
                ("LINEBEFORE",   (0,0),(0,-1), max(1, 3*ratio), colors.HexColor("#f97316")),
            ]))
            story.append(err_row)
    else:
        no_err = Table([[
            Paragraph("✅  감지된 자세 오류 없음", ParagraphStyle(
                "ne", fontName=FB, fontSize=9.5, textColor=colors.HexColor("#166534")))
        ]], colWidths=[usable])
        no_err.setStyle(TableStyle([
            ("BACKGROUND", (0,0),(-1,-1), colors.HexColor("#dcfce7")),
            ("LINEBEFORE", (0,0),(0,-1),  4, colors.HexColor("#22c55e")),
            ("BOX",        (0,0),(-1,-1), 0.5, colors.HexColor("#bbf7d0")),
            ("TOPPADDING",   (0,0),(-1,-1), 10),
            ("BOTTOMPADDING",(0,0),(-1,-1), 10),
            ("LEFTPADDING",  (0,0),(-1,-1), 14),
        ]))
        story.append(no_err)
    story.append(Spacer(1, 30))

    # ════════════════════════════════════════
    # ⑤ AI 트레이너 피드백
    # ════════════════════════════════════════
    story.append(_section_header("AI 트레이너 피드백", FB, F))
    story.append(Spacer(1, 10))

    if feedback:
        import re

        def strip_markdown(text: str) -> str:
            text = re.sub(r'\*{1,3}(.+?)\*{1,3}', r'\1', text)
            text = re.sub(r'^#{1,6}\s*', '', text, flags=re.MULTILINE)
            text = re.sub(r'^\s*[-*]\s+', '• ', text, flags=re.MULTILINE)
            text = re.sub(r'`(.+?)`', r'\1', text)
            return text

        clean = strip_markdown(feedback.strip())

        sBodyFb = ParagraphStyle("bodyFb", fontName=F,  fontSize=9, textColor=colors.HexColor("#1e2028"),
                                 leading=15, leftIndent=6, rightIndent=6)
        sBullet = ParagraphStyle("bullet",  fontName=F,  fontSize=9, textColor=colors.HexColor("#374151"),
                                 leading=15, leftIndent=18, rightIndent=6)
        sEmpty  = ParagraphStyle("sp",      fontName=F,  fontSize=3.5, leading=5)

        inner_paras = []
        for line in clean.split("\n"):
            stripped = line.strip()
            if not stripped:
                inner_paras.append(Paragraph("&nbsp;", sEmpty))
            elif stripped.startswith("•"):
                inner_paras.append(Paragraph(stripped, sBullet))
            else:
                inner_paras.append(Paragraph(stripped, sBodyFb))

        fb_rows = [[p] for p in inner_paras]
        fb_tbl = Table(fb_rows, colWidths=[usable])
        fb_tbl.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,-1), colors.HexColor("#fafff0")),
            ("BOX",          (0,0), (-1,-1), 0.6, C_BORDER_DK),
            ("LINEBEFORE",   (0,0), (0,-1),  3.5, C_LIME),
            ("TOPPADDING",   (0,0), (-1,-1), 2),
            ("BOTTOMPADDING",(0,0), (-1,-1), 2),
            ("LEFTPADDING",  (0,0), (-1,-1), 0),
            ("RIGHTPADDING", (0,0), (-1,-1), 0),
        ]))
        story.append(fb_tbl)
    else:
        no_fb = Table([[
            Paragraph("AI 피드백이 없습니다. 결과 페이지에서 Gemini API Key를 입력하고 피드백을 생성하세요.",
                      ParagraphStyle("no_fb", fontName=F, fontSize=8.5, textColor=C_GRAY, leading=13))
        ]], colWidths=[usable])
        no_fb.setStyle(TableStyle([
            ("BACKGROUND", (0,0),(-1,-1), C_LGRAY),
            ("BOX",        (0,0),(-1,-1), 0.5, C_BORDER_DK),
            ("LINEBEFORE", (0,0),(0,-1),  3, C_BORDER_DK),
            ("TOPPADDING",   (0,0),(-1,-1), 10),
            ("BOTTOMPADDING",(0,0),(-1,-1), 10),
            ("LEFTPADDING",  (0,0),(-1,-1), 14),
        ]))
        story.append(no_fb)
    story.append(Spacer(1, 30))

    # ════════════════════════════════════════
    # ⑥ DTW 구간 분석
    # ════════════════════════════════════════
    if dtw_active and dtw_result:
        phase_dtw = dtw_result.get("phase_dtw_scores", {})
        if phase_dtw:
            story.append(_section_header("DTW 구간 분석", FB, F))
            story.append(Spacer(1, 10))

            # 헤더
            dtw_hdr_style = ParagraphStyle("dh", fontName=FB, fontSize=8, textColor=C_WHITE)
            dtw_hdr = Table([[
                Paragraph("Phase",     dtw_hdr_style),
                Paragraph("DTW 유사도", dtw_hdr_style),
                Paragraph("구간 수",   ParagraphStyle("dh2", fontName=FB, fontSize=8, textColor=C_WHITE, alignment=TA_CENTER)),
                Paragraph("평가",      ParagraphStyle("dh3", fontName=FB, fontSize=8, textColor=C_WHITE, alignment=TA_CENTER)),
            ]], colWidths=[usable*0.28, usable*0.36, usable*0.18, usable*0.18])
            dtw_hdr.setStyle(TableStyle([
                ("BACKGROUND",   (0,0),(-1,-1), colors.HexColor("#1e3a6e")),
                ("VALIGN",       (0,0),(-1,-1), "MIDDLE"),
                ("LEFTPADDING",  (0,0),(-1,-1), 10),
                ("RIGHTPADDING", (0,0),(-1,-1), 10),
                ("TOPPADDING",   (0,0),(-1,-1), 8),
                ("BOTTOMPADDING",(0,0),(-1,-1), 8),
                ("LINEBEFORE",   (0,0),(0,-1),  4, C_BLUE),
            ]))
            story.append(dtw_hdr)

            for i, (phase, sc) in enumerate(phase_dtw.items()):
                segs   = (dtw_result.get("phase_segment_counts") or {}).get(phase, 0)
                is_ok  = sc >= 0.7
                sc_hex = "#3b6de8" if is_ok else "#e8432d"
                label  = "양호" if is_ok else "개선 필요"
                bg     = C_BLUE_BG if i % 2 == 0 else colors.white

                dtw_row = Table([[
                    Paragraph(f"<font size='9' color='#1e2028'>{phase}</font>", sBody),
                    Paragraph(f"<font color='{sc_hex}' size='10'><b>{pct(sc)}</b></font>", sBody),
                    Paragraph(f"<font size='8' color='#6b7280'>{segs}</font>",
                              ParagraphStyle(f"ds_{i}", fontName=F, fontSize=8, textColor=C_GRAY, alignment=TA_CENTER)),
                    Paragraph(f"<font color='{sc_hex}' size='8'><b>{label}</b></font>",
                              ParagraphStyle(f"dl_{i}", fontName=FB, fontSize=8, textColor=C_BLACK, alignment=TA_CENTER)),
                ]], colWidths=[usable*0.28, usable*0.36, usable*0.18, usable*0.18])
                dtw_row.setStyle(TableStyle([
                    ("BACKGROUND",   (0,0),(-1,-1), bg),
                    ("VALIGN",       (0,0),(-1,-1), "MIDDLE"),
                    ("LEFTPADDING",  (0,0),(-1,-1), 10),
                    ("RIGHTPADDING", (0,0),(-1,-1), 10),
                    ("TOPPADDING",   (0,0),(-1,-1), 8),
                    ("BOTTOMPADDING",(0,0),(-1,-1), 8),
                    ("LINEBELOW",    (0,0),(-1,-1), 0.3, C_BORDER),
                ]))
                story.append(dtw_row)

    doc.build(story, canvasmaker=NumberedCanvas)
    buf.seek(0)
    return buf.read()


def _section_header(title: str, FB: str, F: str):
    """섹션 제목 — 왼쪽 라임 라인 + 진한 배경"""
    inner = Table([[
        Paragraph(f"<b>{title}</b>",
                  ParagraphStyle("sh_t", fontName=FB, fontSize=10, textColor=C_DARK))
    ]], colWidths=[None])
    inner.setStyle(TableStyle([
        ("LEFTPADDING",  (0,0),(-1,-1), 10),
        ("RIGHTPADDING", (0,0),(-1,-1), 10),
        ("TOPPADDING",   (0,0),(-1,-1), 6),
        ("BOTTOMPADDING",(0,0),(-1,-1), 6),
        ("LINEBEFORE",   (0,0),(0,-1),  3.5, C_LIME),
        ("LINEBELOW",    (0,0),(-1,-1), 0.5, C_BORDER_DK),
        ("BACKGROUND",   (0,0),(-1,-1), C_LGRAY),
    ]))
    return inner


@report_router.post("/report")
async def download_report(req: ReportRequest):
    """
    POST /analysis/report

    Body:
      analysis_results  : dict         필수 - 분석 결과
      ai_feedback       : str | null   선택 - 프론트에서 이미 생성된 피드백
      gemini_api_key    : str | null   선택 - 서버에서 피드백 자동 생성 시 사용
      generate_feedback : bool         선택 - True면 피드백 없을 때 서버에서 자동 생성 (기본 True)
    """
    pdf_bytes = build_pdf_bytes(req)
    filename  = f"posecoach_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )