# ─────────────────────────────────────────
# report_router.py  (Gemini 피드백 자동생성 포함)
# ─────────────────────────────────────────
import io
from datetime import datetime
from typing import Any, Optional

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_RIGHT
from reportlab.pdfgen import canvas
from pathlib import Path
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.fonts import addMapping

# gemini_feedback 모듈 (없으면 graceful fallback)
try:
    from gemini_feedback import generate_feedback as _generate_feedback
    HAS_GEMINI = True
except ImportError:
    HAS_GEMINI = False
    _generate_feedback = None

report_router = APIRouter(prefix="/analysis", tags=["report"])

BASE_DIR = Path(__file__).resolve().parent
FONT_DIR = BASE_DIR.parent / "assets"

def register_korean_fonts() -> bool:
    reg  = FONT_DIR / "NotoSansKR-Regular.ttf"
    bold = FONT_DIR / "NotoSansKR-Bold.ttf"
    if not reg.exists() or not bold.exists():
        return False
    pdfmetrics.registerFont(TTFont("NotoKR", str(reg)))
    pdfmetrics.registerFont(TTFont("NotoKR-Bold", str(bold)))
    addMapping("NotoKR", 0, 0, "NotoKR")
    addMapping("NotoKR", 0, 1, "NotoKR-Bold")
    addMapping("NotoKR", 1, 0, "NotoKR-Bold")
    addMapping("NotoKR", 1, 1, "NotoKR-Bold")
    return True

W, H    = A4
C_BLACK  = colors.HexColor("#111111")
C_GRAY   = colors.HexColor("#888888")
C_LGRAY  = colors.HexColor("#f4f4f4")
C_BORDER = colors.HexColor("#e0e0e0")
C_GREEN  = colors.HexColor("#c8f135")
C_GREEN_L= colors.HexColor("#f8ffe8")
C_BLUE   = colors.HexColor("#5b8fff")
C_RED    = colors.HexColor("#ff6b35")
C_PURPLE = colors.HexColor("#5b3fa0")

def pct(v: float) -> str: return f"{round(v * 100)}%"
def grade_label(avg: float) -> str:
    if avg >= 0.9: return "S"
    if avg >= 0.7: return "A"
    if avg >= 0.5: return "B"
    return "C"


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._pages: list[dict] = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._pages)
        for i, state in enumerate(self._pages):
            self.__dict__.update(state)
            try:    self.setFont("NotoKR", 8)
            except: self.setFont("Helvetica", 8)
            self.setFillColor(C_GRAY)
            self.drawString(20*mm, 12*mm, f"Generated by PoseCoach AI · {datetime.now().strftime('%Y.%m.%d')}")
            self.drawRightString(W - 20*mm, 12*mm, f"{i + 1} / {total}")
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)


# ── Request 모델 ──
class ReportRequest(BaseModel):
    analysis_results: dict[str, Any]
    ai_feedback: Optional[str] = None        # 프론트에서 이미 생성된 피드백
    gemini_api_key: Optional[str] = None     # 서버에서 피드백 생성 시 사용할 키
    generate_feedback: bool = True           # True면 피드백 없을 때 서버에서 자동 생성


def build_pdf_bytes(req: ReportRequest) -> bytes:
    korean = register_korean_fonts()
    F      = "NotoKR"      if korean else "Helvetica"
    FB     = "NotoKR-Bold" if korean else "Helvetica-Bold"

    res      = req.analysis_results
    feedback = req.ai_feedback or ""

    # ── 1. Gemini 피드백 자동 생성 (프론트 피드백 없고, 서버 생성 요청 시) ──
    if not feedback and req.generate_feedback and HAS_GEMINI:
        try:
            feedback = _generate_feedback(
                analysis_results=res,
                api_key=req.gemini_api_key or None,
            ) or ""
        except Exception as e:
            feedback = ""   # 실패해도 PDF는 계속 생성

    frame_scores = res.get("frame_scores", [])
    error_frames = res.get("error_frames", [])
    dtw_result   = res.get("dtw_result") or {}
    dtw_active   = res.get("dtw_active", False)
    exercise     = res.get("exercise_type", "운동")
    ex_count     = res.get("exercise_count", 0)

    avg_score = (sum(f["score"] for f in frame_scores) / len(frame_scores)) if frame_scores else 0
    dtw_score = dtw_result.get("overall_dtw_score") if dtw_active else None
    combined  = avg_score * 0.7 + dtw_score * 0.3 if dtw_score is not None else avg_score

    by_phase: dict[str, list] = {}
    for f in frame_scores:
        by_phase.setdefault(f["phase"], []).append(f["score"])
    phase_avg = {p: sum(sc) / len(sc) for p, sc in by_phase.items()}
    phase_cnt = {p: len(sc) for p, sc in by_phase.items()}

    err_count: dict[str, int] = {}
    for ef in error_frames:
        for e in ef.get("errors", []):
            err_count[e] = err_count.get(e, 0) + 1
    top_errors = sorted(err_count.items(), key=lambda x: -x[1])[:3]

    # ── 스타일 ──
    sTitle   = ParagraphStyle("title",   fontName=FB, fontSize=18, textColor=C_BLACK, spaceAfter=10)
    sSection = ParagraphStyle("section", fontName=FB, fontSize=11, textColor=C_BLACK, spaceBefore=14, spaceAfter=6)
    sSmall   = ParagraphStyle("small",   fontName=F,  fontSize=8,  textColor=C_GRAY)
    sBody    = ParagraphStyle("body",    fontName=F,  fontSize=9,  textColor=C_BLACK, leading=14)
    sRight   = ParagraphStyle("right",   fontName=F,  fontSize=8,  textColor=C_GRAY,  alignment=TA_RIGHT)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
        leftMargin=20*mm, rightMargin=20*mm, topMargin=18*mm, bottomMargin=22*mm)
    story = []
    usable = W - 40*mm
    ex_kor = {"pushup": "푸시업", "pullup": "풀업"}.get(exercise, exercise)
    grade  = grade_label(combined)

    # ── 헤더 ──
    hdr = Table([[
        Paragraph("<b>PoseCoach</b>", ParagraphStyle("hd", fontName=FB, fontSize=16, textColor=C_BLACK)),
        Paragraph(datetime.now().strftime("%Y.%m.%d"), sRight),
    ]], colWidths=[usable*0.6, usable*0.4])
    hdr.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(0,0),0),("RIGHTPADDING",(-1,-1),(-1,-1),0)]))
    story += [hdr, HRFlowable(width="100%", thickness=1, color=C_BORDER, spaceAfter=12),
              Paragraph(f"{ex_kor} 운동 피드백 리포트", sTitle), Spacer(1,6),
              Paragraph("분석 요약", sSection)]

    # ── 요약 카드 ──
    cw = usable / 4 - 2
    def card(label, val):
        return Paragraph(f"<font color='#888' size='8'>{label}</font><br/><b>{val}</b>",
                         ParagraphStyle(f"c_{label}", fontName=FB, fontSize=14, textColor=C_BLACK, leading=22))
    cards = Table([[
        card("운동 횟수", f"{ex_count}회"),
        card("평균 자세 점수", pct(avg_score)),
        card(f"종합 점수 ({grade})", pct(combined)),
        card("오류 프레임", f"{len(error_frames)}개"),
    ]], colWidths=[cw]*4)
    cards.setStyle(TableStyle([
        ("BOX",(0,0),(0,0),0.8,C_GREEN), ("BACKGROUND",(0,0),(0,0),colors.HexColor("#f9ffe5")),
        ("BOX",(1,0),(-1,0),0.5,C_BORDER), ("BACKGROUND",(1,0),(-1,0),C_LGRAY),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
        ("TOPPADDING",(0,0),(-1,-1),10), ("BOTTOMPADDING",(0,0),(-1,-1),10),
        ("LEFTPADDING",(0,0),(-1,-1),12), ("RIGHTPADDING",(0,0),(-1,-1),8),
    ]))
    story += [cards, Spacer(1,14)]

    # ── Phase별 점수 바 차트 ──
    story.append(Paragraph("Phase별 자세 점수", sSection))
    bar_avail = usable - 55 - 38 - 28
    for phase, avg in sorted(phase_avg.items(), key=lambda x: -x[1]):
        cnt   = phase_cnt.get(phase, 0)
        inner = Table([[""]], colWidths=[max(bar_avail * avg, 1)])
        inner.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(0,0), C_GREEN if avg >= 0.6 else C_RED),
            ("TOPPADDING",(0,0),(0,0),0),("BOTTOMPADDING",(0,0),(0,0),0),
            ("LEFTPADDING",(0,0),(0,0),0),("RIGHTPADDING",(0,0),(0,0),0),
        ]))
        row = Table([[
            Paragraph(f"<font size='8' color='#555'>{phase}</font>", sBody),
            inner,
            Paragraph(f"<b>{pct(avg)}</b>", ParagraphStyle(f"rv_{phase}", fontName=FB, fontSize=9, textColor=C_BLACK)),
            Paragraph(f"<font size='7' color='#aaa'>{cnt}f</font>", sSmall),
        ]], colWidths=[55, bar_avail, 38, 28], rowHeights=18)
        row.setStyle(TableStyle([
            ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
            ("TOPPADDING",(0,0),(-1,-1),2),("BOTTOMPADDING",(0,0),(-1,-1),2),
            ("LEFTPADDING",(0,0),(-1,-1),4),
            ("LINEBELOW",(0,0),(-1,-1),0.3,C_BORDER),
            ("BACKGROUND",(1,0),(1,0),C_LGRAY),
        ]))
        story.append(row)
    story.append(Spacer(1,14))

    # ── 주요 자세 오류 ──
    story.append(Paragraph("주요 자세 오류", sSection))
    if top_errors:
        rows = [[
            Paragraph("<font color='#fff'><b>상세 오류</b></font>", ParagraphStyle("eh1", fontName=FB, fontSize=9, textColor=colors.white)),
            Paragraph("<font color='#fff'><b>횟수</b></font>",      ParagraphStyle("eh2", fontName=FB, fontSize=9, textColor=colors.white)),
        ]]
        for err_name, cnt in top_errors:
            rows.append([
                Paragraph(err_name, sBody),
                Paragraph(f"<font color='#ff6b35'><b>{cnt}회</b></font>", ParagraphStyle("ec", fontName=FB, fontSize=9, textColor=C_BLACK)),
            ])
        et = Table(rows, colWidths=[usable*0.82, usable*0.18])
        et.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),C_RED),
            ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
            ("LEFTPADDING",(0,0),(-1,-1),6),("RIGHTPADDING",(0,0),(-1,-1),10),
            ("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8),
            ("LINEBELOW",(0,0),(-1,-1),0.4,C_BORDER),
            ("ALIGN",(1,1),(1,-1),"RIGHT"),
        ]))
        story.append(et)
    else:
        story.append(Paragraph("감지된 자세 오류 없음 ✅", sBody))
    story.append(Spacer(1,14))

    # ── AI 트레이너 피드백 ──
    story.append(Paragraph("AI 트레이너 피드백", sSection))
    if feedback:
        import re

        def strip_markdown(text: str) -> str:
            """마크다운 기호 제거 → 평문 변환"""
            # **bold** / *italic* → 텍스트만
            text = re.sub(r'\*{1,3}(.+?)\*{1,3}', r'\1', text)
            # ### 헤딩
            text = re.sub(r'^#{1,6}\s*', '', text, flags=re.MULTILINE)
            # - / * 목록 기호
            text = re.sub(r'^\s*[-*]\s+', '• ', text, flags=re.MULTILINE)
            # `code`
            text = re.sub(r'`(.+?)`', r'\1', text)
            return text

        clean = strip_markdown(feedback.strip())

        # 박스 상단 초록 라인
        story.append(Spacer(1, 4))
        # 줄 단위로 세로 나열 (Table 가로 배치 X)
        sBodyFb = ParagraphStyle("bodyFb", fontName=F, fontSize=9,
                                 textColor=C_BLACK, leading=15, leftIndent=14, rightIndent=12)
        sBullet  = ParagraphStyle("bullet", fontName=F, fontSize=9,
                                  textColor=C_BLACK, leading=15, leftIndent=24, rightIndent=12)

        # 전체를 하나의 Table로 감싸서 배경 + 왼쪽 라인 적용
        inner_paras = []
        for line in clean.split("\n"):
            stripped = line.strip()
            if not stripped:
                inner_paras.append(Paragraph("&nbsp;",
                    ParagraphStyle("sp", fontName=F, fontSize=4, leading=6)))
            elif stripped.startswith("•"):
                inner_paras.append(Paragraph(stripped, sBullet))
            else:
                inner_paras.append(Paragraph(stripped, sBodyFb))

        # 각 para를 한 셀짜리 Table row로 쌓기
        fb_rows = [[p] for p in inner_paras]
        fb_tbl  = Table(fb_rows, colWidths=[usable])
        fb_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), C_GREEN_L),
            ("BOX",        (0, 0), (-1, -1), 0.5, C_BORDER),
            ("LINEBEFORE", (0, 0), (0, -1),  3,   C_GREEN),
            ("TOPPADDING",    (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("LEFTPADDING",   (0, 0), (-1, -1), 0),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ]))
        story.append(fb_tbl)
    else:
        story.append(Paragraph(
            "AI 피드백이 없습니다. 결과 페이지에서 Gemini API Key를 입력하고 피드백을 생성하세요.",
            ParagraphStyle("no_fb", fontName=F, fontSize=9, textColor=C_GRAY, leading=14)
        ))
    story.append(Spacer(1, 14))

    # ── DTW 구간 분석 ──
    if dtw_active and dtw_result:
        phase_dtw = dtw_result.get("phase_dtw_scores", {})
        if phase_dtw:
            story.append(Paragraph("DTW 구간 분석", sSection))
            dtw_rows = [[
                Paragraph("<font size='7' color='#fff'>Phase</font>", sSmall),
                Paragraph("<font size='7' color='#fff'>DTW 유사도</font>", sSmall),
                Paragraph("<font size='7' color='#fff'>구간 수</font>", sSmall),
                Paragraph("<font size='7' color='#fff'>평가</font>", sSmall),
            ]]
            for phase, sc in phase_dtw.items():
                segs  = (dtw_result.get("phase_segment_counts") or {}).get(phase, 0)
                hex_c = "#5b8fff" if sc >= 0.7 else "#ff6b35"
                dtw_rows.append([
                    Paragraph(f"<font size='9'>{phase}</font>", sBody),
                    Paragraph(f"<font size='9' color='{hex_c}'><b>{pct(sc)}</b></font>", sBody),
                    Paragraph(f"<font size='8' color='#888'>{segs}</font>", sSmall),
                    Paragraph(f"<font size='8' color='{hex_c}'>{'양호' if sc >= 0.7 else '개선 필요'}</font>", sBody),
                ])
            cw4 = usable / 4
            dtw_tbl = Table(dtw_rows, colWidths=[cw4]*4)
            dtw_tbl.setStyle(TableStyle([
                ("BACKGROUND",(0,0),(-1,0),C_PURPLE),
                ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
                ("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7),
                ("LEFTPADDING",(0,0),(-1,-1),10),
                ("LINEBELOW",(0,0),(-1,-1),0.3,C_BORDER),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, C_LGRAY]),
            ]))
            story.append(dtw_tbl)

    doc.build(story, canvasmaker=NumberedCanvas)
    buf.seek(0)
    return buf.read()


@report_router.post("/report")
async def download_report(req: ReportRequest):
    """
    POST /analysis/report

    Body:
      analysis_results  : dict         필수 - 분석 결과
      ai_feedback       : str | null   선택 - 프론트에서 이미 생성된 피드백
      gemini_api_key    : str | null   선택 - 서버에서 피드백 자동 생성 시 사용
      generate_feedback : bool         선택 - True면 피드백 없을 때 서버에서 자동 생성 (기본 True)
    """
    pdf_bytes = build_pdf_bytes(req)
    filename  = f"posecoach_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )